[package]
name = "fctools"
version = "0.1.0"
edition = "2021"

[dependencies]
# common
async-trait = "0.1.81"
tokio = { version = "1.39.2", features = [
    "process",
    "io-util",
    "fs",
    "time",
    "rt",
] }
# executor
libc = { version = "0.2.155", optional = true }
# process
hyper = { version = "1.4.1", features = ["client"], optional = true }
bytes = { version = "1.6.1", optional = true }
http-body-util = { version = "0.1.2", optional = true }
hyper-client-sockets = { version = "0.1.0", features = [
    "unix",
], optional = true }
hyper-util = { version = "0.1.6", features = [
    "client-legacy",
    "client",
    "http1",
], optional = true }
# vm
serde = { version = "1.0.204", features = ["derive"], optional = true }
serde_json = { version = "1.0.121", optional = true }
http = { version = "1.1.0", optional = true }
# extensions
cidr = { version = "0.2.3", optional = true }

[dev-dependencies]
assert_matches = "1.5.0"
rand = "0.8.5"
run_script = "0.10.1"
tokio = { version = "1.39.2", features = ["macros"] }
uuid = { version = "1.10.0", features = ["v4"] }

fctools = { path = ".", features = ["vm", "metrics-ext", "fcnet-ext"] }

[features]
default = []
shell-spawner = []
executor = ["shell-spawner", "dep:libc"]
process = [
    "executor",
    "dep:hyper",
    "dep:bytes",
    "dep:http-body-util",
    "dep:hyper-client-sockets",
    "dep:hyper-util",
]
vm = ["process", "dep:serde", "dep:serde_json", "dep:http"]
metrics-ext = ["vm"]
fcnet-ext = ["vm", "dep:cidr"]
