[package]
name = "fctools"
version = "0.1.1"
edition = "2021"
description = "An exhaustive, highly modular and extensible host SDK for the Firecracker microVM manager."
license = "MIT"
keywords = ["firecracker", "microvm", "sdk"]
categories = ["virtualization"]
repository = "https://github.com/kanpov/fctools"
readme = "README.md"
exclude = ["/testdata", ".gitattributes", ".gitignore", ".rustfmt.toml"]

[package.metadata.docs.rs]
all-features = true

[profile.dev]
debug = false
strip = "debuginfo"
panic = "abort"
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
strip = "symbols"

[profile.bench.build-override]
opt-level = 3
strip = "symbols"

[dependencies]
# common
async-trait = "0.1.83"
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = [
    "process",
    "io-util",
    "fs",
    "time",
    "rt",
    "sync",
] }
# executor
libc = { version = "0.2.159", optional = true }
# process
hyper = { version = "1.4.1", features = ["client"], optional = true }
bytes = { version = "1.7.2", optional = true }
http-body-util = { version = "0.1.2", optional = true }
hyper-client-sockets = { version = "0.2.0", optional = true }
hyper-util = { version = "0.1.9", features = [
    "client-legacy",
    "client",
    "http1",
], optional = true }
http = { version = "1.1.0", optional = true }
# vm
serde = { version = "1.0.210", features = ["derive"], optional = true }
serde_json = { version = "1.0.128", optional = true }
# extensions
cidr = { version = "0.3.0", optional = true }
tonic = { version = "0.12.3", optional = true, default-features = false, features = [
    "transport",
] }
tower-service = { version = "0.3.3", optional = true }

[dev-dependencies]
assert_matches = "1.5.0"
rand = "0.8.5"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.10.0", features = ["v4"] }
which = "6.0.3"
futures-util = { version = "0.3.31", default-features = false, features = [
    "std",
] }
file-lock = "2.1.11"

fctools = { path = ".", features = ["full"] }

[features]
full = [
    "vm",
    "metrics-ext",
    "fcnet-ext",
    "http-vsock-ext",
    "grpc-vsock-ext",
    "link-local-ext",
    "snapshot-editor-ext",
    "blocking-fs-backend",
]
default = []
# fs backends
blocking-fs-backend = []
# layers
shell-spawner = []
executor = ["shell-spawner", "dep:libc"]
process = [
    "executor",
    "dep:hyper",
    "dep:bytes",
    "dep:http-body-util",
    "hyper-client-sockets/unix",
    "dep:hyper-util",
    "dep:http",
]
vm = ["process", "dep:serde", "dep:serde_json"]
# extensions
metrics-ext = ["dep:serde", "dep:serde_json"]
fcnet-ext = ["shell-spawner", "dep:cidr"]
http-vsock-ext = ["vm", "hyper-client-sockets/firecracker"]
grpc-vsock-ext = [
    "vm",
    "hyper-client-sockets/firecracker",
    "dep:tonic",
    "dep:tower-service",
]
link-local-ext = ["dep:cidr"]
snapshot-editor-ext = ["executor"]
