[package]
name = "fctools"
version = "0.4.0"
edition = "2021"
description = "An exhaustive, highly modular and extensible host SDK for the Firecracker microVM manager."
license = "MIT"
keywords = ["firecracker", "microvm", "sdk"]
categories = ["virtualization"]
repository = "https://github.com/kanpov/fctools"
readme = "README.md"
exclude = ["/testdata", ".gitattributes", ".gitignore", ".rustfmt.toml"]

[package.metadata.docs.rs]
all-features = true

[profile.dev]
debug = false
strip = "debuginfo"
panic = "abort"
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
strip = "symbols"

[profile.bench.build-override]
opt-level = 3
strip = "symbols"

[dependencies]
# common
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = [
    "process",
    "io-util",
    "time",
    "rt",
    "sync",
] }
# fs backends
uuid = { version = "1.11.0", optional = true, features = ["v4"] }
tokio-uring = { version = "0.5.0", optional = true }
# executor
libc = { version = "0.2.160", optional = true }
# process
hyper = { version = "1.5.0", features = ["client"], optional = true }
bytes = { version = "1.7.2", optional = true }
http-body-util = { version = "0.1.2", optional = true }
hyper-client-sockets = { version = "0.2.0", optional = true }
hyper-util = { version = "0.1.9", features = [
    "client-legacy",
    "client",
    "http1",
], optional = true }
http = { version = "1.1.0", optional = true }
# vm
serde = { version = "1.0.210", features = ["derive"], optional = true }
serde_json = { version = "1.0.128", optional = true }
# extensions
cidr = { version = "0.3.0", optional = true }
tonic = { version = "0.12.3", optional = true, default-features = false, features = [
    "transport",
] }
tower-service = { version = "0.3.3", optional = true }

[dev-dependencies]
assert_matches = "1.5.0"
rand = "0.8.5"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.10.0", features = ["v4"] }
which = "6.0.3"
file-lock = "2.1.11"
fcnet = { version = "0.5.0", default-features = false, features = [
    "namespaced",
] }

fctools = { path = ".", features = ["full"] }

[features]
full = [
    "vm",
    "metrics-ext",
    "http-vsock-ext",
    "grpc-vsock-ext",
    "link-local-ext",
    "snapshot-editor-ext",
    "blocking-fs-backend",
    "unsend-proxy-fs-backend",
    "tokio-uring-fs-backend",
]
default = []
# fs backends
fs-backend = []
blocking-fs-backend = ["fs-backend", "tokio/fs"]
unsend-proxy-fs-backend = ["dep:uuid"]
tokio-uring-fs-backend = ["dep:tokio-uring", "tokio/fs"]
# layers
runner = []
executor = ["fs-backend", "runner", "dep:libc"]
process = [
    "executor",
    "dep:hyper",
    "dep:bytes",
    "dep:http-body-util",
    "hyper-client-sockets/unix",
    "dep:hyper-util",
    "dep:http",
]
vm = ["process", "dep:serde", "dep:serde_json"]
# extensions
metrics-ext = ["dep:serde", "dep:serde_json", "tokio/fs"]
http-vsock-ext = ["vm", "hyper-client-sockets/firecracker"]
grpc-vsock-ext = [
    "vm",
    "hyper-client-sockets/firecracker",
    "dep:tonic",
    "dep:tower-service",
]
link-local-ext = ["dep:cidr"]
snapshot-editor-ext = ["executor"]
