[package]
name = "fctools"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
hyper = { version = "1.4.1", features = ["client"] }
bytes = "1.6.1"
http-body-util = "0.1.2"
tokio = { version = "1.39.2", features = [
    "process",
    "io-util",
    "fs",
    "rt",
    "time",
] }
hyper-client-sockets = { version = "0.1.0", features = ["unix"] }
hyper-util = { version = "0.1.6", features = [
    "client-legacy",
    "client",
    "http1",
] }
libc = "0.2.155"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
http = "1.1.0"
uuid = { version = "1.10.0", features = ["v4"] }

[dev-dependencies]
assert_matches = "1.5.0"
rand = "0.8.5"
run_script = "0.10.1"
tokio = { version = "1.38.1", features = ["macros"] }
