[package]
name = "fctools"
version = "0.1.0"
edition = "2021"

[dependencies]
# common
async-trait = "0.1.81"
tokio = { version = "1.39.2", features = [
    "process",
    "io-util",
    "fs",
    "time",
    "rt",
    "sync",
] }
# executor
libc = { version = "0.2.155", optional = true }
# process
hyper = { version = "1.4.1", features = ["client"], optional = true }
bytes = { version = "1.6.1", optional = true }
http-body-util = { version = "0.1.2", optional = true }
hyper-client-sockets = { version = "0.1.0", features = [
    "unix",
], optional = true }
hyper-util = { version = "0.1.6", features = [
    "client-legacy",
    "client",
    "http1",
], optional = true }
# vm
serde = { version = "1.0.204", features = ["derive"], optional = true }
serde_json = { version = "1.0.121", optional = true }
http = { version = "1.1.0", optional = true }
# extensions
cidr = { version = "0.2.3", optional = true }

[dev-dependencies]
assert_matches = "1.5.0"
rand = "0.8.5"
run_script = "0.10.1"
tokio = { version = "1.39.2", features = ["macros"] }
uuid = { version = "1.10.0", features = ["v4"] }

fctools = { path = ".", features = ["full"] }

[features]
default = []
full = [
    "vm",
    "metrics-ext",
    "fcnet-ext",
    "vsock-http-ext",
    "serial-console-ext",
]
# layers
shell-spawner = []
vmm-executor = ["shell-spawner", "dep:libc"]
vmm-process = [
    "vmm-executor",
    "dep:hyper",
    "dep:bytes",
    "dep:http-body-util",
    "dep:hyper-client-sockets",
    "dep:hyper-util",
]
vm = ["vmm-process", "dep:serde", "dep:serde_json", "dep:http"]
# extensions
metrics-ext = ["dep:serde", "dep:serde_json"]
fcnet-ext = ["shell-spawner", "dep:cidr"]
vsock-http-ext = ["vm", "hyper-client-sockets/firecracker"]
serial-console-ext = ["vmm-process"]
